"""将 Assistant ``llm_config`` 同步并引导 Hermes Home 运行配置。

设计：
- 目标 Home 不存在或缺少 ``config.yaml`` 时，自动生成最小可用运行配置
  （目录、SOUL.md、config.yaml、.env），用户无需手工 ``hermes setup``
- 已有配置则只更新 ``model`` 段与对应密钥行，其它项保持不动
- 失败只记日志 / 返回结果，不阻断 Assistant 保存
"""
from __future__ import annotations

import logging
import os
import re
from pathlib import Path
from typing import Any, Dict, Mapping, Optional, Tuple

logger = logging.getLogger(__name__)

_SYNC_MARK = "# managed-by-assistant-llm-sync"

_MINIMAL_SOUL = (
    "You are Hermes Agent, an intelligent AI assistant. "
    "Be helpful, direct, and efficient."
)

_RUNTIME_DIRS = ("cron", "sessions", "logs", "logs/curator", "memories")


def resolve_hermes_home_for_sync() -> Path:
    """解析同步目标 Home：桥 inherit / HERMES_HOME / ~/.hermes。"""
    try:
        import importlib

        _cfg_mod = importlib.import_module("chiby_hermes_bridge.config")
        cfg = _cfg_mod.load_hermes_bridge_config()

        mode = (cfg.hermes_home_mode or "").strip().lower().replace("-", "_")
        if mode == "inherit":
            if cfg.hermes_home_base:
                return Path(cfg.hermes_home_base).expanduser().resolve()
            env_home = (os.environ.get("HERMES_HOME") or "").strip()
            if env_home:
                return Path(env_home).expanduser().resolve()
            return (Path.home() / ".hermes").resolve()
        if cfg.hermes_home_base:
            return Path(cfg.hermes_home_base).expanduser().resolve()
    except Exception as exc:
        logger.debug("resolve hermes home via bridge failed: %s", exc)
    env_home = (os.environ.get("HERMES_HOME") or "").strip()
    if env_home:
        return Path(env_home).expanduser().resolve()
    return (Path.home() / ".hermes").resolve()


def _env_first(*names: str) -> str:
    for n in names:
        v = os.environ.get(n)
        if v is not None and str(v).strip():
            return str(v).strip()
    return ""


def map_assistant_to_hermes_model(
    settings: Mapping[str, Any],
) -> Tuple[Dict[str, Any], Dict[str, str]]:
    """Assistant 生效配置 → (Hermes model 段, .env 键值)。"""
    mode = str(settings.get("mode") or "builtin").strip().lower()
    model = str(settings.get("model") or "").strip()
    base_url = str(settings.get("base_url") or "").strip()
    api_key = str(settings.get("api_key") or "").strip()
    bp = str(settings.get("builtin_provider") or "").strip().lower()

    env_vars: Dict[str, str] = {}
    model_block: Dict[str, Any]

    if mode == "custom":
        model_block = {
            "provider": "custom",
            "default": model or "default",
            "base_url": base_url.rstrip("/") if base_url else "",
        }
        key = api_key or _env_first("OPENAI_API_KEY", "LLM_API_KEY")
        if key:
            env_vars["OPENAI_API_KEY"] = key
        return model_block, env_vars

    if bp == "deepseek":
        model_block = {
            "provider": "deepseek",
            "default": model or "deepseek-chat",
        }
        key = api_key or _env_first("DEEPSEEK_API_KEY", "LLM_API_KEY")
        if key:
            env_vars["DEEPSEEK_API_KEY"] = key
    elif bp == "minimax":
        model_block = {
            "provider": "minimax-cn",
            "default": model or "MiniMax-M2.7",
        }
        key = api_key or _env_first(
            "MINIMAX_CN_API_KEY", "MINIMAX_API_KEY", "MINIMAX_KEY", "LLM_API_KEY"
        )
        if key:
            env_vars["MINIMAX_CN_API_KEY"] = key
    else:
        model_block = {
            "provider": "openai",
            "default": model or "gpt-4o-mini",
        }
        key = api_key or _env_first("OPENAI_API_KEY", "LLM_API_KEY")
        if key:
            env_vars["OPENAI_API_KEY"] = key
        if base_url:
            model_block["base_url"] = base_url.rstrip("/")

    return model_block, env_vars


def ensure_hermes_runtime_home(home: Path) -> Dict[str, Any]:
    """创建 Hermes 运行所需最小目录与文件（幂等）。"""
    home = home.expanduser().resolve()
    created: list[str] = []
    home.mkdir(parents=True, exist_ok=True)

    for sub in _RUNTIME_DIRS:
        d = home / sub
        if not d.is_dir():
            d.mkdir(parents=True, exist_ok=True)
            created.append(str(d.relative_to(home)).replace("\\", "/"))

    soul = home / "SOUL.md"
    if not soul.is_file():
        soul.write_text(_MINIMAL_SOUL + "\n", encoding="utf-8")
        created.append("SOUL.md")

    config_path = home / "config.yaml"
    bootstrapped = False
    if not config_path.is_file():
        import yaml

        stub = {
            # 占位；随后 sync 会写入真实 model
            "model": {
                "provider": "custom",
                "default": "default",
                "base_url": "",
            },
        }
        header = (
            f"{_SYNC_MARK}\n"
            "# Auto-generated by Assistant. Edit model via Assistant LLM settings.\n"
        )
        body = yaml.safe_dump(
            stub, allow_unicode=True, sort_keys=False, default_flow_style=False
        )
        config_path.write_text(header + body, encoding="utf-8")
        created.append("config.yaml")
        bootstrapped = True

    env_path = home / ".env"
    if not env_path.is_file():
        env_path.write_text(
            f"{_SYNC_MARK}\n# API keys synced from Assistant LLM config\n",
            encoding="utf-8",
        )
        created.append(".env")

    return {
        "hermes_home": str(home),
        "bootstrapped_config": bootstrapped,
        "created": created,
    }


def _upsert_dotenv(path: Path, updates: Mapping[str, str]) -> bool:
    """更新或追加键；保留其它行。返回是否写入。"""
    if not updates:
        return False
    lines: list[str] = []
    if path.is_file():
        lines = path.read_text(encoding="utf-8").splitlines()
    key_re = {k: re.compile(rf"^\s*(?:export\s+)?{re.escape(k)}\s*=") for k in updates}
    seen = set()
    out: list[str] = []
    for line in lines:
        replaced = False
        for k, cre in key_re.items():
            if cre.match(line):
                out.append(f"{k}={updates[k]}")
                seen.add(k)
                replaced = True
                break
        if not replaced:
            out.append(line)
    if not seen and _SYNC_MARK not in "\n".join(out):
        out.append("")
        out.append(_SYNC_MARK)
    for k, v in updates.items():
        if k not in seen:
            out.append(f"{k}={v}")
    path.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(out).rstrip() + "\n"
    path.write_text(text, encoding="utf-8")
    return True


def _merge_model_yaml(config_path: Path, model_block: Mapping[str, Any]) -> None:
    import yaml

    raw: Dict[str, Any] = {}
    header_lines: list[str] = []
    if config_path.is_file():
        text = config_path.read_text(encoding="utf-8")
        # 保留文件头注释
        for ln in text.splitlines():
            if ln.startswith("#") or not ln.strip():
                header_lines.append(ln)
            else:
                break
        loaded = yaml.safe_load(text) or {}
        if isinstance(loaded, dict):
            raw = loaded
    existing = raw.get("model")
    if isinstance(existing, dict):
        merged = dict(existing)
        merged.update(dict(model_block))
        if not str(merged.get("base_url") or "").strip():
            if str(merged.get("provider") or "") != "custom":
                merged.pop("base_url", None)
        raw["model"] = merged
    elif isinstance(existing, str) and existing.strip() and not model_block.get("default"):
        block = dict(model_block)
        block["default"] = existing.strip()
        raw["model"] = block
    else:
        raw["model"] = dict(model_block)

    config_path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(
        raw, allow_unicode=True, sort_keys=False, default_flow_style=False
    )
    if header_lines and any(_SYNC_MARK in h for h in header_lines):
        header = "\n".join(header_lines).rstrip() + "\n"
    elif not config_path.is_file() or not header_lines:
        header = f"{_SYNC_MARK}\n# Auto-managed model section from Assistant LLM settings.\n"
    else:
        # 用户原有注释尽量保留
        header = "\n".join(header_lines).rstrip() + "\n" if header_lines else ""
    config_path.write_text(header + body, encoding="utf-8")


def sync_assistant_llm_to_hermes(
    settings: Mapping[str, Any],
    *,
    hermes_home: Optional[Path] = None,
    bootstrap: bool = True,
) -> Dict[str, Any]:
    """把 Assistant LLM 设置写入 Hermes Home（必要时自动生成运行配置）。"""
    home = (hermes_home or resolve_hermes_home_for_sync()).expanduser().resolve()
    config_path = home / "config.yaml"
    env_path = home / ".env"

    bootstrap_info: Dict[str, Any] = {}
    try:
        if bootstrap:
            bootstrap_info = ensure_hermes_runtime_home(home)

        model_block, env_vars = map_assistant_to_hermes_model(settings)
        # 无任何可用模型信息时仍写出 provider 默认，避免 ACP「No LLM provider」
        _merge_model_yaml(config_path, model_block)
        env_updated = False
        if env_vars:
            env_updated = _upsert_dotenv(env_path, env_vars)
        elif not env_path.is_file() and bootstrap:
            env_path.write_text(
                f"{_SYNC_MARK}\n# Add provider API keys or save them in Assistant LLM settings\n",
                encoding="utf-8",
            )

        has_key = bool(env_vars)
        summary = {
            "ok": True,
            "skipped": False,
            "bootstrapped": bool(bootstrap_info.get("bootstrapped_config")),
            "created": list(bootstrap_info.get("created") or []),
            "hermes_home": str(home),
            "config_yaml": str(config_path),
            "model": {
                "provider": model_block.get("provider"),
                "default": model_block.get("default"),
                "base_url": model_block.get("base_url") or "",
            },
            "env_updated": env_updated,
            "env_keys": sorted(env_vars.keys()),
            "warning": (
                None
                if has_key
                else "未写入 API Key（llm_config.api_key 与环境变量皆空）；"
                "Hermes 仍可能报 No LLM provider configured。"
            ),
        }
        logger.info(
            "已同步/引导 Hermes Home: provider=%s model=%s home=%s bootstrapped=%s",
            model_block.get("provider"),
            model_block.get("default"),
            home,
            summary["bootstrapped"],
        )
        return summary
    except Exception as exc:
        logger.warning("同步 Hermes LLM 配置失败: %s", exc, exc_info=True)
        return {
            "ok": False,
            "skipped": False,
            "reason": "sync_error",
            "hermes_home": str(home),
            "error": str(exc)[:300],
        }


def bootstrap_hermes_from_assistant_llm() -> Dict[str, Any]:
    """启动时调用：按当前 Assistant LLM 生效配置引导 Hermes Home。"""
    try:
        from chibycore.llm_config import get_effective_llm_settings

        return sync_assistant_llm_to_hermes(get_effective_llm_settings(), bootstrap=True)
    except Exception as exc:
        logger.warning("启动时 Hermes 引导失败: %s", exc)
        return {"ok": False, "reason": "sync_error", "error": str(exc)[:200]}
